# Copyright 2021-2024 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# [AUTO-GENERATED FILE]

from abc import ABCMeta, abstractmethod

import grpc
from google.protobuf.empty_pb2 import Empty
from ondewo.nlu import common_pb2, server_statistics_pb2
from ondewo.nlu.client import Client
from ondewo.nlu.server_statistics_pb2_grpc import ServerStatisticsServicer
from ondewo.logging.logger import logger


class AutoServerStatisticsServicer(ServerStatisticsServicer):
    """
    [AUTO-GENERATED CLASS]
    generated by: grpc_auto_coder.py
    DO NOT ALTER CODE UNLESS YOU WANT TO DO IT EVERY TIME YOU GENERATE IT!

    used to relay endpoints to the functions defined in:
      >> ./ondewo-nlu-client-python/ondewo/nlu/services/server_statistics.py
    any child class is expected to have a .client attribute to send the service calls to (metaclass-enforced)
    all function/endpoint calls are logged
    override functions if other functionality than a client call is needed

    [original docstring]
    Server project statistics

    """
    __metaclass__ = ABCMeta

    @property
    @abstractmethod
    def client(self) -> Client:
        pass

    def GetProjectCount(self, request: Empty, context: grpc.ServicerContext) -> common_pb2.StatResponse:
        """
        [AUTO-GENERATED FUNCTION]
        Returns the count of projects in the CAI server

        """
        logger.info("relaying GetProjectCount() to nlu-client...")
        response = self.client.services.server_statistics.get_project_count()
        return response

    def GetUserProjectCount(self, request: server_statistics_pb2.GetUserProjectCountRequest, context: grpc.ServicerContext) -> common_pb2.StatResponse:
        """
        [AUTO-GENERATED FUNCTION]
        Returns the count of projects of a user

        """
        logger.info("relaying GetUserProjectCount() to nlu-client...")
        response = self.client.services.server_statistics.get_user_project_count(request=request)
        return response

    def GetUserCount(self, request: Empty, context: grpc.ServicerContext) -> common_pb2.StatResponse:
        """
        [AUTO-GENERATED FUNCTION]
        Returns the users count within a project

        """
        logger.info("relaying GetUserCount() to nlu-client...")
        response = self.client.services.server_statistics.get_project_count()
        return response

# [make flake8 shut up]
