# Copyright 2021 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# [AUTO-GENERATED FILE]

from abc import ABCMeta, abstractmethod

import grpc
from google.protobuf.empty_pb2 import Empty
from ondewo.nlu import session_pb2
from ondewo.nlu.client import Client
from ondewo.nlu.session_pb2_grpc import SessionsServicer
from ondewo.logging.logger import logger


class AutoSessionsServicer(SessionsServicer):
    """
    [AUTO-GENERATED CLASS]
    generated by: grpc_auto_coder.py
    DO NOT ALTER CODE UNLESS YOU WANT TO DO IT EVERY TIME YOU GENERATE IT!

    used to relay endpoints to the functions defined in:
      >> ./ondewo-nlu-client-python/ondewo/nlu/services/sessions.py
    any child class is expected to have a .client attribute to send the service calls to (metaclass-enforced)
    all function/endpoint calls are logged
    override functions if other functionality than a client call is needed

    [original docstring]
    A session represents an interaction with a user. You retrieve user input

    """
    __metaclass__ = ABCMeta

    @property
    @abstractmethod
    def client(self) -> Client:
        pass

    def DetectIntent(self, request: session_pb2.DetectIntentRequest, context: grpc.ServicerContext) -> session_pb2.DetectIntentResponse:
        """
        [AUTO-GENERATED FUNCTION]
        Processes a natural language query and returns structured, actionable data

        """
        logger.info("relaying DetectIntent() to nlu-client...")
        response = self.client.services.sessions.detect_intent(request=request)
        return response

    def StreamingDetectIntent(self, request_iterator: session_pb2.StreamingDetectIntentRequest, context: grpc.ServicerContext) -> session_pb2.StreamingDetectIntentResponse:
        """
        [AUTO-GENERATED FUNCTION]
        Processes a natural language query in audio format in a streaming fashion

        """
        logger.info("relaying StreamingDetectIntent() to nlu-client...")
        response = self.client.services.sessions.streaming_detect_intent(request=request_iterator)
        return response

    def ListSessions(self, request: session_pb2.ListSessionsRequest, context: grpc.ServicerContext) -> session_pb2.ListSessionsResponse:
        """
        [AUTO-GENERATED FUNCTION]
        *** SESSION RELATED ENDPOINTS *** //

        """
        logger.info("relaying ListSessions() to nlu-client...")
        response = self.client.services.sessions.list_sessions(request=request)
        return response

    def GetSession(self, request: session_pb2.GetSessionRequest, context: grpc.ServicerContext) -> session_pb2.Session:
        """
        [AUTO-GENERATED FUNCTION]
        GetSession: returns a session(=conversation) from ondewo-kb

        """
        logger.info("relaying GetSession() to nlu-client...")
        response = self.client.services.sessions.get_session(request=request)
        return response

    def TrackSessionStep(self, request: session_pb2.TrackSessionStepRequest, context: grpc.ServicerContext) -> session_pb2.Session:
        """
        [AUTO-GENERATED FUNCTION]
        TrackSessionStep: append to an existing session; creates it if not existing

        """
        logger.info("relaying TrackSessionStep() to nlu-client...")
        response = self.client.services.sessions.track_session_step(request=request)
        return response

    def DeleteSession(self, request: session_pb2.DeleteSessionRequest, context: grpc.ServicerContext) -> Empty:
        """
        [AUTO-GENERATED FUNCTION]
        DeleteSession: delete a session(=conversation) from ondewo-kb (for testing only)

        """
        logger.info("relaying DeleteSession() to nlu-client...")
        response = self.client.services.sessions.delete_session(request=request)
        return response

    def ListSessionLabels(self, request: session_pb2.ListSessionLabelsRequest, context: grpc.ServicerContext) -> session_pb2.ListSessionLabelsResponse:
        """
        [AUTO-GENERATED FUNCTION]
        *** SESSION-LABEL RELATED ENDPOINTS *** //

        """
        logger.info("relaying ListSessionLabels() to nlu-client...")
        response = self.client.services.sessions.list_session_labels(request=request)
        return response

    def AddSessionLabels(self, request: session_pb2.AddSessionLabelsRequest, context: grpc.ServicerContext) -> session_pb2.Session:
        """
        [AUTO-GENERATED FUNCTION]
        Missing associated documentation comment in .proto file.
        """
        logger.info("relaying AddSessionLabels() to nlu-client...")
        response = self.client.services.sessions.add_session_labels(request=request)
        return response

    def RemoveSessionLabels(self, request: session_pb2.RemoveSessionLabelsRequest, context: grpc.ServicerContext) -> session_pb2.Session:
        """
        [AUTO-GENERATED FUNCTION]
        Missing associated documentation comment in .proto file.
        """
        logger.info("relaying RemoveSessionLabels() to nlu-client...")
        response = self.client.services.sessions.remove_session_labels(request=request)
        return response

    def ListSessionReviews(self, request: session_pb2.ListSessionReviewsRequest, context: grpc.ServicerContext) -> session_pb2.ListSessionReviewsResponse:
        """
        [AUTO-GENERATED FUNCTION]
        *** SESSION-REVIEW RELATED ENDPOINTS *** //

        """
        logger.info("relaying ListSessionReviews() to nlu-client...")
        response = self.client.services.sessions.list_session_reviews(request=request)
        return response

    def GetSessionReview(self, request: session_pb2.GetSessionReviewRequest, context: grpc.ServicerContext) -> session_pb2.SessionReview:
        """
        [AUTO-GENERATED FUNCTION]
        GetSessionReview:

        """
        logger.info("relaying GetSessionReview() to nlu-client...")
        response = self.client.services.sessions.get_session_review(request=request)
        return response

    def GetLatestSessionReview(self, request: session_pb2.GetLatestSessionReviewRequest, context: grpc.ServicerContext) -> session_pb2.SessionReview:
        """
        [AUTO-GENERATED FUNCTION]
        GetLatestSessionReview:

        """
        logger.info("relaying GetLatestSessionReview() to nlu-client...")
        response = self.client.services.sessions.get_latest_session_review(request=request)
        return response

    def CreateSessionReview(self, request: session_pb2.CreateSessionReviewRequest, context: grpc.ServicerContext) -> session_pb2.SessionReview:
        """
        [AUTO-GENERATED FUNCTION]
        CreateSessionReview:

        """
        logger.info("relaying CreateSessionReview() to nlu-client...")
        response = self.client.services.sessions.create_session_review(request=request)
        return response

# [make flake8 shut up]
